<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>/mnt/code/code/git/C#/StardewMod/CentralStorageInterface/CentralStorageInterface/</BaseOutputPath>
    <Gamepath>/mnt/games/SteamLibrary/steamapps/common/Stardew Valley/</Gamepath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>

</Project>
